# Generated by Django 5.2 on 2025-04-25 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseChannelStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("views", models.IntegerField()),
                ("subscribers", models.IntegerField()),
                (
                    "session_file_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Channels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("photo_url", models.URLField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PrivateChannelStats",
            fields=[
                (
                    "basechannelstats_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="account.basechannelstats",
                    ),
                ),
                ("forwards", models.IntegerField()),
                ("reactions", models.IntegerField()),
                ("engagement_rate", models.FloatField()),
                ("retention_rate", models.FloatField(blank=True, null=True)),
            ],
            bases=("account.basechannelstats",),
        ),
        migrations.AddField(
            model_name="basechannelstats",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.channels"
            ),
        ),
        migrations.CreateModel(
            name="UserChannelAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_owner", models.BooleanField(default=False)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.channels",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "channel")},
            },
        ),
        migrations.AddField(
            model_name="channels",
            name="users",
            field=models.ManyToManyField(
                related_name="channels",
                through="account.UserChannelAccess",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
