# Generated by Django 5.2 on 2025-04-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_basechannelstats_views_post_forwards_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privatechannelstats",
            name="forwards",
        ),
        migrations.RemoveField(
            model_name="privatechannelstats",
            name="reactions",
        ),
    ]
