# Generated by Django 5.2.1 on 2025-06-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_privatechannelstats_forwards_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privatechannelstats",
            name="basechannelstats_ptr",
        ),
        migrations.DeleteModel(
            name="BaseChannelStats",
        ),
        migrations.DeleteModel(
            name="PrivateChannelStats",
        ),
    ]
