# Generated by Django 5.2.1 on 2025-06-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_remove_privatechannelstats_basechannelstats_ptr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channels",
            name="photo_url",
        ),
        migrations.AddField(
            model_name="channels",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="channels_pics/"),
        ),
    ]
